DROP TABLE IF EXISTS MEMBER_TGT;

CREATE TABLE MEMBER_TGT COMMENT '회원' (
    MBR_ID      VARCHAR(10)     NOT NULL    COMMENT '회원ID'
    , NAME        VARCHAR(100)                COMMENT '회원명'
    , PRIMARY KEY (MBR_ID)
);